// Bundles the mod's sources, the pure game engine and zod into the single
// hooks module the cc-idle plugin ships (plugins/cc-idle/hooks/register.js).
// A mod loads no packages and has no Node, so everything it needs travels in
// that one readable file; `claude-code` stays an import the engine provides.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const here = (path) => fileURLToPath(new URL(path, import.meta.url));

await build({
  entryPoints: [here('./src/register.tsx')],
  outfile: here('../../plugins/cc-idle/hooks/register.js'),
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  external: ['claude-code'],
  // The engine needs only the Node-free part of @ccidle/shared; its index
  // also exports Node-only config and save-file helpers.
  alias: { '@ccidle/shared': here('../shared/src/pure.ts') },
  mainFields: ['module', 'main'],
  jsx: 'transform',
  jsxFactory: 'h',
  jsxFragment: 'Fragment',
  legalComments: 'inline',
  banner: {
    js: '// GENERATED by packages/mod/build.mjs from packages/mod/src and packages/game. Do not edit by hand.'
  },
  logLevel: 'warning'
});
